import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { Search, X } from 'lucide-react'
import { FaFacebookF, FaLink, FaWhatsapp, FaXTwitter } from 'react-icons/fa6'
import StoreHeader from '../home/components/StoreHeader'
import StoreFooter from '../home/components/StoreFooter'
import './StorePages.css'
const API = import.meta.env.VITE_API_URL || 'http://localhost:5000/api'; const headers = () => ({ 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('token') || ''}` }); const src = (x?: string) => x?.startsWith('/') ? API.replace('/api', '') + x : x; const money = (n: number) => `$${n.toFixed(2)}`; type P = { _id: string; slug: string; title: string; price: number; description?: string; images?: string[]; category?: { name: string }; variants?: { _id: string; name: string; price?: number }[] };
function Shell({ children }: { children: React.ReactNode }) { return <div className="storefront"><StoreHeader />{children}<StoreFooter /></div> }
export function CollectionPage() { const [p, setP] = useState<P[]>([]); useEffect(() => { fetch(API + '/products?limit=100').then(r => r.json()).then(b => setP(b.data || [])) }, []); return <Shell><main className="shop"><p className="eyebrow">THE COLLECTION</p><h1>Objects for everyday ritual.</h1><div className="products">{p.map(x => <Link to={`/products/${x.slug}`} key={x._id}><img src={src(x.images?.[0])} /><small>{x.category?.name || 'SUGRA'}</small><h2>{x.title}</h2><b>{money(x.price)}</b></Link>)}</div></main></Shell> }
export function ProductPage() { const { slug = '' } = useParams(); const [p, setP] = useState<P>(); const [v, setV] = useState(''); const [m, setM] = useState(''); useEffect(() => { fetch(API + '/products/' + slug).then(r => r.json()).then(b => setP(b.data)) }, [slug]); async function add() { if (!p) return; const r = await fetch(API + '/cart/items', { method: 'POST', headers: headers(), body: JSON.stringify({ productId: p._id, variantId: v || undefined, quantity: 1 }) }); setM(r.ok ? 'Added to your bag.' : localStorage.getItem('token') ? 'Unable to add product.' : 'Please sign in before adding to your bag.') }; if (!p) return <Shell><main className="shop">Loading…</main></Shell>; return <Shell><main className="detail"><img src={src(p.images?.[0])} /><div><p className="eyebrow">{p.category?.name || 'SUGRA'}</p><h1>{p.title}</h1><b>{money(p.price)}</b><p>{p.description}</p>{p.variants?.length ? <select value={v} onChange={e => setV(e.target.value)}><option value="">Choose an option</option>{p.variants.map(x => <option value={x._id} key={x._id}>{x.name} — {money(x.price ?? p.price)}</option>)}</select> : null}<button onClick={() => void add()}>Add to bag</button><p>{m}</p></div></main></Shell> }
export function CartPage() { const [i, setI] = useState<any[]>([]); const [s, setS] = useState(0); const [m, setM] = useState(''); const load = async () => { const r = await fetch(API + '/cart', { headers: headers() }); if (!r.ok) { setM('Please sign in to view your bag.'); return } const b = await r.json(); setI(b.data.items); setS(b.data.summary.subtotal) }; useEffect(() => { void load() }, []); const change = async (x: any, q: number) => { await fetch(API + `/cart/items/${x.id}`, { method: 'PATCH', headers: headers(), body: JSON.stringify({ quantity: q }) }); void load() }; return <Shell><main className="shop"><p className="eyebrow">YOUR BAG</p><h1>Shopping bag</h1>{m || !i.length ? <p>{m || 'Your bag is empty.'}</p> : <div className="cart"> <section>{i.map(x => <article key={x.id}><img src={src(x.product.images?.[0])} /><div><h2>{x.product.title}</h2><p>{x.variant?.name}</p><b>{money(x.unitPrice)}</b></div><div><button disabled={x.quantity === 1} onClick={() => void change(x, x.quantity - 1)}>−</button> {x.quantity} <button onClick={() => void change(x, x.quantity + 1)}>+</button></div></article>)}</section><aside><h2>Order summary</h2><p>Subtotal <b>{money(s)}</b></p><Link to="/checkout">Checkout</Link></aside></div>}</main></Shell> }
type WishlistItem = { _id: string; product: P }
export function WishlistPage() {
  const [items, setItems] = useState<WishlistItem[]>([])
  const [recommendations, setRecommendations] = useState<P[]>([])
  const [selected, setSelected] = useState<string[]>([])
  const [query, setQuery] = useState('')
  const [message, setMessage] = useState('')
  const [loading, setLoading] = useState(true)
  const load = async () => {
    setLoading(true)
    const response = await fetch(API + '/wishlist', { headers: headers() })
    if (!response.ok) { setMessage(localStorage.getItem('token') ? 'Unable to load your wishlist.' : 'Please sign in to view your wishlist.'); setLoading(false); return }
    const body = await response.json(); setItems(body.data.items || []); setSelected([]); setMessage(''); setLoading(false)
  }
  useEffect(() => {
    void load()
    fetch(API + '/products?limit=8').then(response => response.json()).then(body => setRecommendations(body.data || [])).catch(() => setRecommendations([]))
  }, [])
  const visible = items.filter(item => item.product.title.toLowerCase().includes(query.toLowerCase()))
  const wishlistProductIds = new Set(items.map(item => item.product._id))
  const recommendedProducts = recommendations.filter(product => !wishlistProductIds.has(product._id)).slice(0, 4)
  const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id])
  const remove = async (id: string) => { await fetch(API + `/wishlist/items/${id}`, { method: 'DELETE', headers: headers() }); void load() }
  const moveToCart = async (item: WishlistItem) => { const response = await fetch(API + '/cart/items', { method: 'POST', headers: headers(), body: JSON.stringify({ productId: item.product._id, quantity: 1 }) }); if (response.ok) void remove(item._id); else setMessage('Unable to move this item to your bag.') }
  const share = (url: string) => window.open(url, '_blank', 'noopener,noreferrer')
  return <Shell><main className="wishlist-page">
    <div className="wishlist-heading"><h1>My wishlist</h1><div className="wishlist-share" aria-label="Share wishlist"><button onClick={() => share('https://www.facebook.com/sharer/sharer.php?u=' + encodeURIComponent(window.location.href))} aria-label="Share on Facebook"><FaFacebookF /></button><button onClick={() => share('https://twitter.com/intent/tweet?url=' + encodeURIComponent(window.location.href))} aria-label="Share on X"><FaXTwitter /></button><button onClick={() => share('https://wa.me/?text=' + encodeURIComponent(window.location.href))} aria-label="Share on WhatsApp"><FaWhatsapp /></button><button onClick={() => share('mailto:?subject=My wishlist&body=' + encodeURIComponent(window.location.href))} aria-label="Share by email">@</button><button onClick={() => void navigator.clipboard?.writeText(window.location.href)} aria-label="Copy wishlist link"><FaLink /></button></div></div>
    <label className="wishlist-search"><Search size={18} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search item" aria-label="Search wishlist" /></label>
    <label className="wishlist-select-all"><input type="checkbox" checked={visible.length > 0 && selected.length === visible.length} onChange={() => setSelected(selected.length === visible.length ? [] : visible.map(item => item._id))} /> Select All</label>
    {message && <p className="wishlist-message">{message}</p>}
    {loading ? <p className="wishlist-message">Loading wishlist...</p> : !visible.length && !message ? <p className="wishlist-message">Your wishlist is empty.</p> : <div className="wishlist-grid">{visible.map(item => <article className="wishlist-card" key={item._id}><div className="wishlist-image"><img src={src(item.product.images?.[0])} alt={item.product.title} /><input type="checkbox" checked={selected.includes(item._id)} onChange={() => toggle(item._id)} aria-label={`Select ${item.product.title}`} /><button onClick={() => void remove(item._id)} aria-label={`Remove ${item.product.title}`}><X size={20} /></button></div><h2>{item.product.title}</h2><b>{money(item.product.price)}</b><div className="wishlist-quantity"><button aria-label="Decrease quantity">−</button><span>1</span><button aria-label="Increase quantity">+</button></div><button className="wishlist-cart" onClick={() => void moveToCart(item)}>Move to cart</button></article>)}</div>}
    <section className="wishlist-recommendations"><h2 className="wishlist-recommendation">You may also like</h2><div className="wishlist-recommendation-grid">{recommendedProducts.map(product => <Link to={`/products/${product.slug}`} className="wishlist-recommendation-card" key={product._id}><img src={src(product.images?.[0])} alt={product.title} /><h3>{product.title}</h3><b>{money(product.price)}</b></Link>)}</div></section>
  </main></Shell>
}
export function CheckoutPage() { const nav = useNavigate(); const [e, setE] = useState(''); async function submit(x: React.FormEvent<HTMLFormElement>) { x.preventDefault(); const a = await fetch(API + '/addresses', { method: 'POST', headers: headers(), body: JSON.stringify(Object.fromEntries(new FormData(x.currentTarget))) }); if (!a.ok) { setE('Please sign in and enter valid delivery details.'); return } const b = await a.json(); const o = await fetch(API + '/orders', { method: 'POST', headers: headers(), body: JSON.stringify({ addressId: b.data._id }) }); if (!o.ok) { setE('Your order could not be placed.'); return } nav('/order-success') } return <Shell><main className="shop checkout"><p className="eyebrow">SECURE CHECKOUT</p><h1>Delivery details</h1><form onSubmit={submit}>{[['recipientName', 'Full name'], ['phone', 'Phone'], ['line1', 'Address line 1'], ['line2', 'Address line 2'], ['city', 'City'], ['state', 'State'], ['postalCode', 'Postal code'], ['country', 'Country']].map(([n, p]) => <input name={n} placeholder={p} required={n !== 'line2'} key={n} />)}<input name="label" value="Home" readOnly /><button>Place order</button><p className="error">{e}</p></form></main></Shell> }
export function SuccessPage() { return <Shell><main className="shop"><p className="eyebrow">ORDER CONFIRMED</p><h1>Thank you for your order.</h1><Link to="/collections">Continue shopping</Link></main></Shell> }
