import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import type { Category, Order, Product, Review } from '../types'
import { money, pic, pill, when } from '../components/ui'
import ProductForm from '../components/ProductForm'

type Kind = 'Products' | 'Categories' | 'Inventory' | 'Orders' | 'Reviews'
type RecordItem = Product | Category | Order | Review
const API = import.meta.env.VITE_API_URL || 'http://localhost:5000/api'
const endpoints: Record<Kind, string> = { Products: '/admin/products', Categories: '/admin/categories', Inventory: '/admin/inventory', Orders: '/admin/orders?limit=100', Reviews: '/admin/reviews' }

export default function ManagementPage({ kind, token }: { kind: Kind; token: string }) {
  const [data, setData] = useState<RecordItem[]>([])
  const [error, setError] = useState(''); const [q, setQ] = useState(''); const [filter, setFilter] = useState(''); const [add, setAdd] = useState(false); const [addCategory, setAddCategory] = useState(false)
  const [editCategory, setEditCategory] = useState<Category | null>(null); const [editProduct, setEditProduct] = useState<Product | null>(null)
  const [adjustment, setAdjustment] = useState<{ id: string; title: string; scope: object } | null>(null)
  const load = async () => { try { setError(''); const r = await fetch(API + endpoints[kind], { headers: { Authorization: `Bearer ${token}` } }); const b = await r.json(); if (!r.ok) throw Error(b.message); setData(Array.isArray(b.data) ? b.data : []) } catch (e) { setError(e instanceof Error ? e.message : 'Could not load data') } }
  useEffect(() => { void load() }, [kind, token])
  const patch = async (path: string, body: object) => { const r = await fetch(API + path, { method: 'PATCH', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify(body) }); if (!r.ok) { const b = await r.json(); setError(b.message || 'Update failed'); return } void load() }
  const remove = async (id: string, title: string) => { if (!window.confirm(`Delete ${title}? This cannot be undone.`)) return; const r = await fetch(API + `/products/${id}`, { method: 'DELETE', headers: { Authorization: `Bearer ${token}` } }); if (!r.ok) { const b = await r.json(); setError(b.message || 'Delete failed'); return } void load() }
  const createCategory = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); const r = await fetch(API + '/categories', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ name: f.get('name'), description: f.get('description'), image: f.get('image'), isActive: f.get('isActive') === 'on' }) }); if (!r.ok) { const b = await r.json(); setError(b.message || 'Could not create category'); return } setAddCategory(false); void load() }
  const list = useMemo(() => data.filter(x => { const a = x as Product & Category & Order & Review; const name = a.title || a.name || a.orderNumber || a.product?.title || ''; return name.toLowerCase().includes(q.toLowerCase()) && (!filter || a.status === filter || (filter === 'low' && 'stock' in a && a.stock > 0 && a.stock <= 5) || (filter === 'out' && 'stock' in a && a.stock === 0)) }), [data, q, filter])
  if (add && kind === 'Products') return <ProductForm token={token} onClose={() => setAdd(false)} onCreated={() => { setAdd(false); void load() }} />
  if (editProduct && kind === 'Products') return <ProductForm token={token} product={editProduct} onClose={() => setEditProduct(null)} onCreated={() => { setEditProduct(null); void load() }} />
  const saveAdjustment = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!adjustment) return; const value = Number(new FormData(event.currentTarget).get('quantity')); if (!Number.isInteger(value) || value === 0) return; await patch(`/admin/inventory/${adjustment.id}`, { quantity: value, ...adjustment.scope }); setAdjustment(null) }
  return <>{error && <p className="error">{error}</p>}<div className="toolbar"><input value={q} onChange={e => setQ(e.target.value)} placeholder={`Search ${kind.toLowerCase()}...`} /><select value={filter} onChange={e => setFilter(e.target.value)}><option value="">All statuses</option>{kind === 'Products' && <><option value="active">Active</option><option value="draft">Draft</option><option value="archived">Archived</option></>}{kind === 'Inventory' && <><option value="low">Low stock</option><option value="out">Out of stock</option></>}<option value="pending">Pending</option></select>{kind === 'Products' && <button className="primary" onClick={() => setAdd(true)}>+ Add product</button>}{kind === 'Categories' && <button className="primary" onClick={() => setAddCategory(true)}>+ Add category</button>}</div>{addCategory && <form className="create" onSubmit={createCategory}><input name="name" placeholder="Category name" required /><input name="description" placeholder="Short description" /><input name="image" type="url" placeholder="Image URL (optional)" /><label><input name="isActive" type="checkbox" defaultChecked /> Active</label><button className="primary">Save category</button><button type="button" onClick={() => setAddCategory(false)}>Cancel</button></form>}{editCategory && <CategoryEditor category={editCategory} onCancel={() => setEditCategory(null)} onSaved={() => { setEditCategory(null); void load() }} token={token} />}<Table kind={kind} data={list} patch={patch} remove={remove} onEditCategory={setEditCategory} onEditProduct={setEditProduct} onAdjust={(id, title, scope) => setAdjustment({ id, title, scope })} />{adjustment && <div className="modal-backdrop"><form className="modal" onSubmit={saveAdjustment}><button type="button" className="modal-close" onClick={() => setAdjustment(null)}>×</button><h2>Adjust stock</h2><p>{adjustment.title}</p><label className="field"><span>Quantity change</span><input name="quantity" type="number" step="1" placeholder="Example: +5 or -2" autoFocus required /></label><div className="modal-actions"><button type="button" onClick={() => setAdjustment(null)}>Cancel</button><button className="primary">Apply adjustment</button></div></form></div>}</>
}

function CategoryEditor({ category, token, onCancel, onSaved }: { category: Category; token: string; onCancel: () => void; onSaved: () => void }) {
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); const name = String(f.get('name') || '').trim(); const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); const response = await fetch(API + `/categories/${category._id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ name, slug, description: f.get('description'), image: f.get('image'), isActive: f.get('isActive') === 'on' }) }); if (!response.ok) return; onSaved() }
  return <form className="create" onSubmit={submit}><strong>Edit category</strong><input name="name" defaultValue={category.name} placeholder="Category name" required /><input name="description" defaultValue={category.description || ''} placeholder="Short description" /><input name="image" type="url" defaultValue={category.image || ''} placeholder="Image URL (optional)" /><label><input name="isActive" type="checkbox" defaultChecked={category.isActive} /> Active</label><button className="primary">Save changes</button><button type="button" onClick={onCancel}>Cancel</button></form>
}

function Table({ kind, data, patch, remove, onEditCategory, onEditProduct, onAdjust }: { kind: Kind; data: RecordItem[]; patch: (path: string, body: object) => Promise<void>; remove: (id: string, title: string) => Promise<void>; onEditCategory?: (category: Category) => void; onEditProduct?: (product: Product) => void; onAdjust?: (id: string, title: string, scope: object) => void }) {
  if (!data.length) return <section className="panel empty">No {kind.toLowerCase()} found.</section>
  const adjust = (id: string, title: string, scope: object = {}) => onAdjust?.(id, title, scope)
  if (kind === 'Products') return <section className="table"><table><thead><tr>{['Product', 'Category', 'Price', 'Inventory', 'Status', 'Updated', ''].map(x => <th key={x}>{x}</th>)}</tr></thead><tbody>{(data as Product[]).map(p => <tr key={p._id}><td className="id">{pic(p.images?.[0])}<span><b>{p.title}</b><small>{p.sku || 'No SKU'}</small></span></td><td>{p.category?.name || 'Uncategorized'}</td><td>{money(p.price)}</td><td>{p.stock} in stock</td><td>{pill(p.status)}</td><td>{when(p.updatedAt)}</td><td><button onClick={() => onEditProduct?.(p)}>Edit</button><select value={p.status} onChange={e => void patch(`/products/${p._id}`, { status: e.target.value })}><option>active</option><option>draft</option><option>archived</option></select><button className="danger" onClick={() => void remove(p._id, p.title)}>Delete</button></td></tr>)}</tbody></table></section>
  if (kind === 'Categories') return <section className="table"><table><thead><tr>{['Category', 'Products', 'Status', 'Updated', ''].map(x => <th key={x}>{x}</th>)}</tr></thead><tbody>{(data as Category[]).map(c => <tr key={c._id}><td className="id">{pic(c.image)}<b>{c.name}</b></td><td>{c.productCount || 0} products</td><td>{pill(c.isActive ? 'Active' : 'Inactive')}</td><td>{when(c.updatedAt)}</td><td><button onClick={() => onEditCategory?.(c)}>Edit</button><button onClick={() => void patch(`/categories/${c._id}`, { isActive: !c.isActive })}>{c.isActive ? 'Deactivate' : 'Activate'}</button></td></tr>)}</tbody></table></section>
  if (kind === 'Inventory') return <section className="table"><table><thead><tr>{['Product', 'SKU', 'Price', 'Stock', 'Status', 'Update stock'].map(x => <th key={x}>{x}</th>)}</tr></thead><tbody>{(data as Product[]).map(p => <tr key={p._id}><td className="id">{pic(p.images?.[0])}<span><b>{p.title}</b><small>Default variant</small></span></td><td>{p.sku || '—'}</td><td>{money(p.price)}</td><td><b>{p.stock}</b></td><td>{pill(p.stock === 0 ? 'Out of stock' : p.stock <= 5 ? 'Low stock' : 'In stock')}</td><td><button onClick={() => adjust(p._id, p.title)}>Product</button>{p.variants?.map(variant => <button key={variant._id || variant.sku} onClick={() => variant._id && adjust(p._id, `${p.title} / ${variant.name}`, { variantId: variant._id })}>{variant.name}</button>)}{p.inventoryByLocation?.map(location => <button key={location.name} onClick={() => adjust(p._id, `${p.title} / ${location.name}`, { locationName: location.name })}>{location.name}</button>)}</td></tr>)}</tbody></table></section>
  if (kind === 'Orders') return <section className="table"><table><thead><tr>{['Order', 'Customer', 'Total', 'Payment', 'Status', 'Date', ''].map(x => <th key={x}>{x}</th>)}</tr></thead><tbody>{(data as Order[]).map(o => <tr key={o._id}><td className="id">{pic(o.items[0]?.image)}<span><b>{o.orderNumber}</b><small>{o.items[0]?.title}</small></span></td><td>{o.user?.name || '—'}</td><td>{money(o.total)}</td><td>{pill(o.payment.status)}</td><td>{pill(o.status)}</td><td>{when(o.createdAt)}</td><td><select value={o.status} onChange={e => void patch(`/admin/orders/${o._id}/status`, { status: e.target.value })}>{['pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled'].map(x => <option key={x}>{x}</option>)}</select></td></tr>)}</tbody></table></section>
  return <section className="table"><table><thead><tr>{['Product', 'Customer', 'Rating', 'Review', 'Status', 'Date', ''].map(x => <th key={x}>{x}</th>)}</tr></thead><tbody>{(data as Review[]).map(r => <tr key={r._id}><td className="id">{pic(r.product?.images?.[0])}<b>{r.product?.title || 'Deleted product'}</b></td><td>{r.user?.name || '—'}</td><td className="stars">{'★'.repeat(r.rating)}{'☆'.repeat(5 - r.rating)}</td><td>{r.comment}</td><td>{pill(r.status)}</td><td>{when(r.createdAt)}</td><td><select value={r.status} onChange={e => void patch(`/admin/reviews/${r._id}/status`, { status: e.target.value })}><option>pending</option><option>approved</option><option>rejected</option></select></td></tr>)}</tbody></table></section>
}
